import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Geist, Geist_Mono, Mystery_Quest } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const mysteryQuest = Mystery_Quest({
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Hell's Kitchen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen bg-white">
         <Navbar/>
       {children}
         
       
      </body>
    </html>
  );
}
